apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankdash-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankdash-frontend
  template:
    metadata:
      labels:
        app: bankdash-frontend
    spec:
      containers:
        - name: bankdash-frontend
          image: nelsonobazee12518/bankdash-frontend:v3
          ports:
            - containerPort: 80  # Changed from 3000 to 80
          env:
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: bankdash-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Changed from 3000 to 80
      nodePort: 30036
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80